version: "3.8"
services:
  mongodb:
    image: 'mongo:4.4.18'
    volumes: 
      - data:/data/db
    env_file:
      - ./env/mongo.env
  backend:
    build: ./backend
    ports:
      - '4000:4000'
    command: ["npm", "start"]
    volumes:
      - ./backend:/app
      - logs:/app/logs
      - /app/node_modules
    env_file:
      - ./env/node.env
    depends_on:
        - mongodb
  frontend:
    build: ./frontEnd
    ports:
      - "5173:5173"
    command: ["npm", "run", "dev"]
    volumes:
      - ./frontEnd:/app
      - /app/node_modules
    env_file:
      - ./env/react.env
    depends_on:
      - backend
  npm:
    image: node
    working_dir: /app
    entrypoint: ['npm']
    volumes:
      - ./backend:/app
      - /app/node_modules

volumes:
  data:
  logs:
    