version: "3.8"
services:
  mongodb:
    image: 'mongo:4.4.18'
    volumes: 
      - data:/data/db
    env_file:
      - ./env/mongo.env
  backend:
    build: ./backend
    ports:
      - '80:80'
    command: ["npm", "start"]
    volumes:
      - logs:/app/logs
      - ./Backend:/app
      - /app/node_modules
    env_file:
      - ./env/node.env
    depends_on:
        - mongodb
  frontend:
    build: ./FrontEnd
    ports:
      - "80:80"
    command: ["npm", "run", "dev"]
    volumes:
      - ./FrontEnd:/app
      - /app/node_modules
    env_file:
      - ./env/react.env
    depends_on:
      - backend

volumes:
  data:
  logs:
    